
###

POST http://ph01.gd.xianyuyigongti.com:9002/chis/*.jsonRequest?d=0469b8022eecac89d9848348645e1ba48ec019c3c0ccf9c66b23fc7b5a678c8b3c7d1423fcae6cdfbb2c34be33b56c6a75b0bacfbe04ec785ed3d14c3790fd4b593ec2c7b095a818d8305807690f1bd21b1d25f28569cb7ea9f8e6e0b5e49559ed1efbea1c5b1aeb80f4515fde7c
cookie:JSESSIONID=8C293E7429632E909839700839DF7627; 
Origin: http://ph01.gd.xianyuyigongti.com:9002
Referer: http://ph01.gd.xianyuyigongti.com:9002/chis/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
accept: application/json, text/plain, */*
accept-language: zh-CN,zh;q=0.9,en;q=0.8
content-type: application/json;charset=UTF-8

{
    "serviceId": "chis.hypertensionVisitService",
    "schema": "chis.application.hy.schemas.MDC_HypertensionVisit",
    "method": "execute",
    "body": {
        "drugId1":"17028",
        "visitId": "0000000000267219",
        "phrId": "网络000000000000001",
        "personName": "",
        "sexCode": "",
        "birthday": "",
        "idCard": "",
        "phoneNumber": "",
        "regionCode": "",
        "empiId": "4ee0acad017142bf90ef60faac897b87",
        "visitDate": "2023-05-10",
        "visitWay": "1",
        "visitEffect": "1",
        "noVisitReason": "",
        "noVisitReasonOtherNot": "",
        "currentSymptoms": "",
        "otherSymptoms": "",
        "constriction": "51",
        "diastolic": "50",
        "weight": "11",
        "targetWeight": "11",
        "bmi": "11",
        "targetBmi": "11",
        "heartRate": "11",
        "targetHeartRate": "",
        "otherSigns": "11",
        "smokeCount": "11",
        "targetSmokeCount": "11",
        "drinkCount": "11",
        "drinkTypeCode": "",
        "targetDrinkCount": "11",
        "trainTimesWeek": "11",
        "targetTrainTimesWeek": "11",
        "trainMinute": "11",
        "targetTrainMinute": "11",
        "loseWeight": "2",
        "salt": "",
        "targetSalt": "",
        "cure": "1",
        "noCureReason": "",
        "medicine": "1",
        "medicineNot": "",
        "medicineOtherNot": "",
        "medicineBadEffect": "n",
        "medicineBadEffectText": "",
        "auxiliaryCheck": "",
        "psychologyChange": "",
        "obeyDoctor": "",
        "riskiness": "",
        "targetHurt": "",
        "complication": "",
        "complicationIncrease": "",
        "riskLevel": "1",
        "riskUpdateReason": "",
        "visitEvaluate": "1",
        "healthProposal": "",
        "drugNames1": "艾叶",
        "medicineType1": "31",
    "everyDayTime1":"2",
    "oneDosage1":"2",
        "medicineUnit1": 5,
"medicineUnit1_text": "包",
        "drugNames2": "",
        "medicineType2": "",
        "everyDayTime2": "",
        "oneDosage2": "",
        "medicineUnit2": "",
        "drugNames3": "",
        "medicineType3": "",
        "everyDayTime3": "",
        "oneDosage3": "",
        "medicineUnit3": "",
        "drugNames4": "",
        "medicineType4": "",
        "everyDayTime4": "",
        "oneDosage4": "",
        "medicineUnit4": "",
        "drugNames5": "",
        "medicineType5": "",
        "everyDayTime5": "",
        "oneDosage5": "",
        "medicineUnit5": "",
        "agencyAndDept": "",
        "referralReason": "",
        "nextDate": "2023-05-24",
        "visitDoctor": "605999",
        "visitUnit": "445202605",
        "treatEffect": "",
        "cardiovascularEvent": "1",
        "waistLine": "",
        "hypertensionGroup": "",
        "incorrectMedicine": "",
        "noMedicine": "",
        "otherReason": "",
        "healthRecipe": "",
        "nonMedicineWay": "",
        "acceptDegree": "",
        "inputUnit": "445202605",
        "inputUser": "605999",
        "inputDate": "2023-05-31 15:11:21",
        "manaDoctorId": "",
        "lateInput": "",
        "lastModifyUser": "605999",
        "lastModifyUnit": "445202605",
        "lastModifyDate": "2023-05-31 16:28:57",
        "status": "0",
        "regionCode_text": "",
        "lastVisitId": "0000000000000000",
        "nextPlanId": "0000000002577863",
        "height": 100,
        "planDate": "2023-05-10",
        "planId": "0000000002577861",
        "endDate": "2023-05-15T00:00:00",
        "beginDate": "2023-05-05T00:00:00",
        "fixGroupDate": "",
        "sn": null,
        "nonStandard": "【目前症状,摄盐情况,目标摄盐情况,心理调整,遵医行为】未填写<br>&nbsp;&nbsp;&nbsp;&nbsp;【用药情况】未填写",
        "standard": 0,
        "completeLevel": "80%",
        "medicineList": [],
        "needAssess": false,
        "controlBad": false,
        "hypertensionGroupName": "",
        "needInsertPlan": false,
        "needReferral": false,
        "needChangeGroup": false
    },
    "op": "update",
    "serviceAction": "saveHypertensionVisit"
}
###
POST http://ph01.gd.xianyuyigongti.com:9002/chis/*.jsonRequest?d=04a84dbfb01f9b8182984616d5e8edcf996d0beeefc9016e981a2d64b3bef275388f75a3ff8167e52882793580473118c4da99c8dc95f37bf257856f92c54fc3754b79933c376023b71fba0880273637c2e0966fbf025e9e8760bc8d4ec8ebdf123574f7f3158e8067b7e02e391f
Content-Type: application/json
cookie:JSESSIONID=746F187F7F0D69A19FE7862B3135B22B; 
Origin: http://ph01.gd.xianyuyigongti.com:9002
Referer: http://ph01.gd.xianyuyigongti.com:9002/chis/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0

{"method":"execute",
"op":"update",
"schema":"chis.application.hy.schemas.MDC_HypertensionVisit",
"serviceAction":"saveHypertensionVisit",
"serviceId":"chis.hypertensionVisitService",
"body":{
"drugNames1": "艾叶",
    
    "riskUpdateReason":"","acceptDegree":"","agencyAndDept":"","auxiliaryCheck":"",
"birthday":"","bmi":"11.00","cardiovascularEvent":"1","complication":"",
"complicationIncrease":"","constriction":"51","controlBad":true,"cure":"1",
"currentSymptoms":"0","diastolic":"50","drinkCount":"11.0","drinkTypeCode":"",
"empiId":"4ee0acad017142bf90ef60faac897b87","updateReason":null,
"fixGroupDate":"2023-04-22","healthProposal":"","healthRecipe":"",
"heartRate":"11","height":"170","hypertensionGroup":null,"hypertensionGroupName":"",
"idCard":"","incorrectMedicine":"","inputDate":"2023-05-10T00:00:00","inputUnit":null,
"inputUser":"605999","lastModifyDate":"0001-01-01T00:00:00","lastModifyUnit":null,
"lastModifyUser":"605999","lateInput":"",
"loseWeight":"1","manaDoctorId":"","medicine":"1",
"medicineBadEffectText":"",
"medicineNot":"","medicineOtherNot":"","needAssess":"",
"needChangeGroup":false
,"needReferral":true,
"nextDate":"2023-05-24","nextPlanId":"0000000002577863","noMedicine":"",
"noVisitReason":"","nonMedicineWay":"","obeyDoctor":"0","oldGroup":null,"otherReason":"",
"otherSigns":"11","otherSymptoms":"","personName":"","phoneNumber":"",
"phrId":"\u7F51\u7EDC000000000000001","planDate":"2023-04-22","planId":"0000000002577861",
"psychologyChange":"0","referralReason":"","regionCode":"","regionCode_text":"","riskLevel":"",
"riskiness":"","salt":"","sexCode":"","smokeCount":"11","sn":1,"status":"0","targetBmi":"11.00",
"targetDrinkCount":"11.0","targetHurt":"","targetSalt":"","targetSmokeCount":"11","targetTrainMinute":"11",
"targetTrainTimesWeek":"11","targetWeight":"11.00","trainMinute":"11","trainTimesWeek":"11","treatEffect":"",
"visitDate":"2023-05-10","visitDoctor":"605100","visitEffect":"1","visitEvaluate":"1","visitId":"0000000000267135",
"visitUnit":"445202605","visitWay":"1","vmList":[],"waistLine":"","weight":"11.00","medicineIds":{},"drugId1":"17028",
"everyDayTime1":"3","oneDosage1":"3",
"medicineUnit1": 5,
"medicineUnit1_text": "包",
"medicineType1": "31",
"medicineBadEffect": "n",
"needInsertPlan": true,
"standard": 0,
"status": "0",
"cardiovascularEvent": "1",
"healthProposal":"",
"loseWeight":2,
"days1": "1",
"days2": "1",
"days3": "1",
"days4": "1",
"days5": "1",
"days6": "1",
"days7": "1",
"days8": "1",
"days9": "1",
"days10": "1"
}}


###
POST http://ph01.gd.xianyuyigongti.com:9002/chis/*.jsonRequest?d=0469b8022eecac89d9848348645e1ba48ec019c3c0ccf9c66b23fc7b5a678c8b3c7d1423fcae6cdfbb2c34be33b56c6a75b0bacfbe04ec785ed3d14c3790fd4b593ec2c7b095a818d8305807690f1bd21b1d25f28569cb7ea9f8e6e0b5e49559ed1efbea1c5b1aeb80f4515fde7c
Content-Type: application/json
cookie:JSESSIONID=6CDD43E832B8FCDF3801EA80CAC08BBA; 
Origin: http://ph01.gd.xianyuyigongti.com:9002
Referer: http://ph01.gd.xianyuyigongti.com:9002/chis/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0

{"method":"execute","op":"update",
"schema":"chis.application.hy.schemas.MDC_HypertensionVisit",
"serviceAction":"saveHypertensionVisit",
"serviceId":"chis.hypertensionVisitService",
"body":{
"empiId":"4ee0acad017142bf90ef60faac897b87",
"visitDate":"2023-05-17","visitWay":"1",
"visitEffect":"1","noVisitReason":null,
"noVisitReasonOtherNot":"","currentSymptoms":"0",
"otherSymptoms":"","constriction":"51","noCureReason":"",
"medicine":"1","medicineNot":"","medicineOtherNot":"",
"medicineBadEffect":"","medicineBadEffectText":"",
"medicineList":[],"needAssess":false,
"controlBad":false,"needChangeGroup":false,
"riskUpdateReason":"","acceptDegree":"",
"agencyAndDept":"","auxiliaryCheck":"",
"bmi":"11.00","cardiovascularEvent":"1",
"complication":"","complicationIncrease":"",
"cure":"1","diastolic":"50","drinkCount":"11.0",
"drinkTypeCode":"","updateReason":null,"fixGroupDate":"2023-04-22","healthProposal":"",
"healthRecipe":"","heartRate":"11","height":"170","hypertensionGroup":null,"hypertensionGroupName":"",
"incorrectMedicine":"","inputDate":"2023-05-17T00:00:00","inputUnit":"445202605","inputUser":"605999",
"lastModifyUnit":"lastModifyUnit","lastModifyUser":"605999","lateInput":"",
"loseWeight":"1","manaDoctorId":"","needInsertPlan":false,
"needReferral":false,"nextDate":"2023-05-24","nextPlanId":"0000000002492377",
"noMedicine":"","nonMedicineWay":"","obeyDoctor":"1","oldGroup":null,"otherReason":"",
"otherSigns":"11","phrId":"网络000000000000001","planDate":"2023-04-22",
"planId":"0000000002579026","psychologyChange":"0","referralReason":"","regionCode_text":"",
"riskLevel":"","riskiness":"","salt":"","smokeCount":"11","sn":1,"status":"0","targetBmi":"11.00",
"targetDrinkCount":"11.0","targetHurt":"","targetSalt":"","targetSmokeCount":"11",
"targetTrainMinute":"11","targetTrainTimesWeek":"11","targetWeight":"11","trainMinute":"11",
"trainTimesWeek":"11","treatEffect":"","visitDoctor":"605999","visitEvaluate":"1","visitId":"0000000000267219",
"visitUnit":"445202605","waistLine":"",
"weight":"11.00","drugNames1":"Sabin株脊灰灭活疫苗","drugId1":"11425",
"medicineType1":"22","everyDayTime1":"1","oneDosage1":"1.00","medicineUnit1":"6",     "standard": 0}}

###
POST http://localhost:81/EHR/eHR_HealthRecordQueryByTimespan
Content-Type: application/json
account: 605999

{
  "start": "2013-01-01",
  "end": "2023-01-01",
  "pageNo": 1,
  "pageSize": 20
}


###
POST http://ph01.gd.xianyuyigongti.com:9002/chis/*.jsonRequest?start0&limit=20
Content-Type: application/json
Cookie: JSESSIONID=7E3F8C0335852E9D5936914FF0E44065;
Origin: http://ph01.gd.xianyuyigongti.com:9002
Referer: http://ph01.gd.xianyuyigongti.com:9002/chis/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0

{"cnd":
["or",["and",["gt",
["$","to_char(b.createTime,'yyyy-MM-dd')"],["s","2013-01-01"]],
["lt",["$","to_char(b.createTime,'yyyy-MM-dd')"],["s","2023-01-01"]]],
["and",["eq",["$","a.status"],["s","0"]],["gt",["$","to_char(b.lastModifyTime,'yyyy-MM-dd')"],["s","2013-01-01"]],["lt",["$","to_char(b.lastModifyTime,'yyyy-MM-dd')"],["s","2023-01-01"]]]],"schema":"chis.application.hr.schemas.EHR_HealthRecordAndMPIList","action":"","serviceId":"chis.listSqlQuery","method":"execute","pageNo":1,"pageSize":20}
